apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: etl
  name: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
        - env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DBHost
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DBUser
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DBPassword
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DBName
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: DBPort
          image: localhost:5000/etl
          name: etl
